"""Manifest and project configuration.

``.research-harness/manifest.toml`` records what was vendored (versions,
adoption timestamp) and ``.research-harness/config.toml`` records
project-level policy the researcher may edit.  Both are read with
:mod:`tomllib`; writing is done by hand because the standard library has no
TOML writer and RDH stays dependency-free (SPEC 6).
"""

from __future__ import annotations

import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from . import BUNDLE_VERSION, MANIFEST_SCHEMA_VERSION, MIN_RUNTIME_VERSION, RUNTIME_VERSION
from .errors import HarnessError, NotAdoptedError
from .records import RISK_LEVELS
from .util import atomic_write, iso_timestamp

HARNESS_DIRNAME = ".research-harness"
MANIFEST_NAME = "manifest.toml"
CONFIG_NAME = "config.toml"

#: Risk levels ordered from cheapest to most consequential.
_RISK_ORDER = {name: index for index, name in enumerate(RISK_LEVELS)}


def _toml_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def toml_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(toml_value(v) for v in value) + "]"
    return f'"{_toml_escape(str(value))}"'


def render_toml(data: dict[str, Any]) -> str:
    """Render a shallow ``{scalars..., table: {scalars...}}`` mapping."""
    lines: list[str] = []
    for key, value in data.items():
        if isinstance(value, dict):
            continue
        lines.append(f"{key} = {toml_value(value)}")
    for key, value in data.items():
        if not isinstance(value, dict):
            continue
        lines.append("")
        lines.append(f"[{key}]")
        for sub_key, sub_value in value.items():
            lines.append(f"{sub_key} = {toml_value(sub_value)}")
    return "\n".join(lines).strip() + "\n"


def load_toml(path: Path) -> dict[str, Any]:
    try:
        with path.open("rb") as handle:
            return tomllib.load(handle)
    except FileNotFoundError:
        raise HarnessError(f"missing file: {path}") from None
    except tomllib.TOMLDecodeError as exc:
        raise HarnessError(f"invalid TOML in {path}: {exc}") from None


@dataclass
class Manifest:
    schema_version: int = MANIFEST_SCHEMA_VERSION
    bundle_version: str = BUNDLE_VERSION
    runtime_version: str = RUNTIME_VERSION
    min_runtime_version: str = MIN_RUNTIME_VERSION
    adopted_at: str = field(default_factory=iso_timestamp)
    upgraded_at: str | None = None
    source: str = "research-development-harness"

    def to_dict(self) -> dict[str, Any]:
        data: dict[str, Any] = {
            "schema_version": self.schema_version,
            "bundle_version": self.bundle_version,
            "runtime_version": self.runtime_version,
            "source": self.source,
            "adopted_at": self.adopted_at,
        }
        if self.upgraded_at:
            data["upgraded_at"] = self.upgraded_at
        data["compatibility"] = {"min_runtime_version": self.min_runtime_version}
        return data

    def render(self) -> str:
        header = (
            "# Research Development Harness manifest.\n"
            "# Generated by `rh adopt` / `rh upgrade`. Edit only if you know why.\n\n"
        )
        return header + render_toml(self.to_dict())

    @classmethod
    def parse(cls, data: dict[str, Any]) -> "Manifest":
        compatibility = data.get("compatibility") or {}
        return cls(
            schema_version=int(data.get("schema_version", MANIFEST_SCHEMA_VERSION)),
            bundle_version=str(data.get("bundle_version", "0.0.0")),
            runtime_version=str(data.get("runtime_version", "0.0.0")),
            min_runtime_version=str(compatibility.get("min_runtime_version", "0.0.0")),
            adopted_at=str(data.get("adopted_at", "")),
            upgraded_at=data.get("upgraded_at"),
            source=str(data.get("source", "research-development-harness")),
        )

    @classmethod
    def load(cls, path: Path) -> "Manifest":
        return cls.parse(load_toml(path))


@dataclass
class Config:
    """Project policy the researcher may tune after adoption."""

    project_name: str = ""
    github_repo: str | None = None
    remote: str = "origin"
    branch_prefix: str = "rh/"
    default_risk: str = "medium"
    #: Minimum risk level at which each gate is required.
    design_gate_from: str = "medium"
    evidence_gate_from: str = "medium"
    knowledge_gate_from: str = "medium"
    #: Issue label applied to Work Issues (empty disables labelling).
    work_label: str = ""
    raw: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "project": {"name": self.project_name},
            "github": {"repo": self.github_repo or "", "remote": self.remote},
            "work": {
                "branch_prefix": self.branch_prefix,
                "default_risk": self.default_risk,
                "label": self.work_label,
            },
            "gates": {
                "design_from": self.design_gate_from,
                "evidence_from": self.evidence_gate_from,
                "knowledge_from": self.knowledge_gate_from,
            },
        }

    def render(self) -> str:
        header = (
            "# Research Development Harness project configuration.\n"
            "# Safe to edit. `rh upgrade` never overwrites this file.\n"
            "#\n"
            "# gates.*_from: lowest work risk at which that Human Gate is required\n"
            "#               (low | medium | high). Gates can always be overridden\n"
            "#               by the researcher with an explicit Gate Record.\n\n"
        )
        return header + render_toml(self.to_dict())

    @classmethod
    def parse(cls, data: dict[str, Any]) -> "Config":
        project = data.get("project") or {}
        github = data.get("github") or {}
        work = data.get("work") or {}
        gates = data.get("gates") or {}
        repo = str(github.get("repo", "")).strip()
        return cls(
            project_name=str(project.get("name", "")),
            github_repo=repo or None,
            remote=str(github.get("remote", "origin")) or "origin",
            branch_prefix=str(work.get("branch_prefix", "rh/")),
            default_risk=str(work.get("default_risk", "medium")),
            design_gate_from=str(gates.get("design_from", "medium")),
            evidence_gate_from=str(gates.get("evidence_from", "medium")),
            knowledge_gate_from=str(gates.get("knowledge_from", "medium")),
            work_label=str(work.get("label", "")),
            raw=data,
        )

    @classmethod
    def load(cls, path: Path) -> "Config":
        if not path.exists():
            return cls()
        return cls.parse(load_toml(path))

    # ------------------------------------------------------------------ policy

    def gate_required(self, gate: str, risk: str, *, evidence_required: bool = False) -> bool:
        """Deterministic gate policy (SPEC 19).

        This is threshold arithmetic over declared risk, not a judgement about
        the research itself — the semantic call belongs to the agent.
        """
        risk_index = _RISK_ORDER.get(risk, _RISK_ORDER["medium"])
        thresholds = {
            "design": self.design_gate_from,
            "evidence": self.evidence_gate_from,
            "knowledge": self.knowledge_gate_from,
        }
        if gate == "deviation":
            # Deviation gates are raised semantically by the agent, never
            # scheduled by risk alone.
            return False
        if gate == "evidence" and not evidence_required:
            return False
        threshold = thresholds.get(gate)
        if threshold is None:
            return False
        return risk_index >= _RISK_ORDER.get(threshold, _RISK_ORDER["medium"])

    def required_gates(self, risk: str, *, evidence_required: bool = False) -> list[str]:
        return [
            gate
            for gate in ("design", "evidence", "knowledge")
            if self.gate_required(gate, risk, evidence_required=evidence_required)
        ]


@dataclass
class Installation:
    """A repository with ``.research-harness`` vendored into it."""

    root: Path
    harness_dir: Path
    manifest: Manifest
    config: Config

    @property
    def bin_path(self) -> Path:
        return self.harness_dir / "bin" / "rh"

    @property
    def runtime_dir(self) -> Path:
        return self.harness_dir / "runtime"

    @property
    def workflows_dir(self) -> Path:
        return self.harness_dir / "workflows"

    @property
    def templates_dir(self) -> Path:
        return self.harness_dir / "templates"

    @property
    def policy_dir(self) -> Path:
        return self.harness_dir / "policy"

    @classmethod
    def locate(cls, root: Path) -> "Installation":
        harness_dir = Path(root) / HARNESS_DIRNAME
        manifest_path = harness_dir / MANIFEST_NAME
        if not manifest_path.exists():
            raise NotAdoptedError(
                f"no RDH installation in {root}",
                hint="Adopt it first: ./bin/rh adopt <path> from the harness distribution repository.",
            )
        return cls(
            root=Path(root),
            harness_dir=harness_dir,
            manifest=Manifest.load(manifest_path),
            config=Config.load(harness_dir / CONFIG_NAME),
        )

    @classmethod
    def locate_optional(cls, root: Path) -> "Installation | None":
        try:
            return cls.locate(root)
        except (NotAdoptedError, HarnessError):
            return None


def write_manifest(harness_dir: Path, manifest: Manifest) -> None:
    atomic_write(harness_dir / MANIFEST_NAME, manifest.render())


def write_config(harness_dir: Path, config: Config) -> None:
    atomic_write(harness_dir / CONFIG_NAME, config.render())
